#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ ! -f $SCRIPTPATH/config/config.ini ]; then
	echo 'Error! Config file does not exist (config/config.ini). Leaving..'
fi

python3 $SCRIPTPATH/src/main.py --config $SCRIPTPATH/config/config.ini
